### ISSUE TITLE
twrp-3.2.3 fails to decrypt /data on redmi note 4 (mido)

### ISSUE THREAD

**Issue by mcastillof** [TheScarastic/android_device_xiaomi_mido#23]
Hello, I'm having problems to mount /data after its decryption on TWRP 3.2.3 in mido. This is the [recovery.log](https://github.com/TheScarastic/android_device_xiaomi_mido/files/2300638/recovery.log).

The same issue was posted in [TeamWin/Team-Win-Recovery-Project repo](https://github.com/TeamWin/Team-Win-Recovery-Project/issues/1287), and they have asked to post the issue in the device tree. 

If you need more info, please just ask for it.

**Comment by pajadam** [comment]
I had the same issue with TWRP and some other recoveries.

But [OrangeFox Recovery](https://forum.xda-developers.com/redmi-note-4/xiaomi-redmi-note-4-snapdragon-roms-kernels-recoveries--other-development/recovery-orangefox-recovery-project-t3775933) saves the day - it works from version R6.1. I'm currently running version R8.1.

Regards, Adam.

**Comment by giner** [comment]
@mcastillof, you may want to check this https://github.com/omnirom/android_bootable_recovery/issues/224

**Comment by mcastillof** [comment]
TWRP 3.2.3-1 is working fine as you said in that issue. Thanks @giner.
