### ISSUE TITLE
TWRP not working 

### ISSUE THREAD

**Issue by vl197602** [TheScarastic/android_device_xiaomi_mido#3]
DElete this partition /hyp emmc /dev/block/bootdevice/by-name/hyp 
we dont have it at all and it cause an error while make a backup

**Comment by TheScarastic** [comment]
https://github.com/TeamWin/android_device_xiaomi_mido/commit/32f9c72be41d6f9f4216cb314dcc069f3f0a6565

will make new build shortly

**Comment by vl197602** [comment]
Do you have a test build оf TWRP?

2017-03-14 9:21 GMT+03:00 Abhishek Aggarwal <notifications@github.com>:
