### ISSUE TITLE
Consult on the device_xiaomi_mido problem

### ISSUE THREAD

**Issue by Aromer-room** [TheScarastic/android_device_xiaomi_mido#5]
I'm sorry to bother you, I've got some problems while compiling
xiaomi_mido and want to get your help

IES/audio.primary.msm8953_intermediates/audio_extn/ssr.d )"
hardware/qcom/audio-caf/msm8937/hal/audio_extn/ssr.c:39:10: fatal
error: 'surround_rec_interface.h' file not found

**Comment by TheScarastic** [comment]
Pick https://review.lineageos.org/#/c/163217/ this will fix your error
